function cfg = NI_ConfigureSession()
% Opens a dialog to configure the NIDAQ session. Saves the result as a 
% struct for use with the other NI functions. Also saves the last-used
% settings to a file so they appear again the next time NIDAQ is used.
    
    cfgFileName = [fileparts(mfilename('fullpath')) '\settings.cfg'];

    if exist(cfgFileName, 'file')        
        [~, settings] = NI_ImportConfig();
    else
        settings = {'Data Log', '10000', '60', '1', 'ui', '1'};
    end

    dialog = inputdlg ( ...
        {'Log Name', ... 
        'Sampling Frequency (Hz)', ...
        'Recording Duration (s) (0=indefinite)', ...
        'Data Preview Mode' ...
        'Output Folder (enter "ui" for browser)', ...
        'Save As Text?'}, ...
        'Configure DAQ Session', 1, ...
        settings);
    
    cfg = struct('SampleRate', str2double(dialog{2}), ...
        'Duration', str2double(dialog{3}), ...
        'PreviewMode', str2double(dialog{4}), ...
        'LogName', dialog{1}, ...
        'LogFolder', dialog{5}, ...
        'SaveAsText', str2double(dialog{6}));
    
    NI_ExportConfig(cfg);

end

