function NI_ExportConfig( cfg )

cfgFileName = [fileparts(mfilename('fullpath')) '\settings.cfg'];
fid = fopen(cfgFileName, 'w+');

ch_str = '%s';
if isscalar(cfg.Channels); ch_str = '[%s]'; end

fmt = [ ...
    'DeviceIndex\t%d\r\n', ...
    'SubsystemIndex\t%d\r\n', ...
    'ActiveChannels\t' ch_str '\r\n', ...
    'SampleRate\t%d\r\n', ...
    'RecordDuration\t%d\r\n', ...
    'PreviewMode\t%d\r\n', ...
    'LogNamePrefix\t%s\r\n', ...
    'LogDirectory\t%s' ...
];

fprintf(fid, fmt, ...
    cfg.DeviceIndex, ...
    cfg.SubsystemIndex, ...
    mat2str(cfg.Channels), ...
    cfg.SampleRate, ...
    cfg.Duration, ...
    cfg.PreviewMode, ...
    cfg.LogName, ...
    cfg.LogDirectory );
 
fclose(fid);



